import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCart } from '../context/CartContext';
import { Link } from 'react-router-dom';
//@ts-ignore
import empty_Cart from "../assets/empty_Cart.png";
const CartPage = () => {
    const { cart, removeFromCart, totalPrice } = useCart();
    if (cart.length === 0) {
        return (_jsxs("div", { className: "empty-cart-container", style: { padding: '4rem', textAlign: 'center' }, children: [_jsx("img", { className: "empty_img", src: empty_Cart, alt: "empty-bag", style: { width: '230px', marginBottom: '0.5rem' } }), _jsx("h2", { style: { fontWeight: 700, color: '#282c3f' }, children: "Hey, it feels so light!" }), _jsx("p", { style: { color: '#94969f', marginBottom: '2rem' }, children: "There is nothing in your bag. Let's add some items." }), _jsx(Link, { to: "/", className: "btn-outline", children: "ADD ITEMS FROM LIST" })] }));
    }
    return (_jsxs("div", { className: "cart-container", children: [_jsxs("div", { className: "cart-items-section", children: [_jsx("div", { className: "cart-header-actions" }), cart.map((item) => (_jsxs("div", { className: "cart-item-card", children: [_jsx("img", { src: item.image, alt: item.title, className: "cart-img" }), _jsxs("div", { className: "cart-item-info", children: [_jsx("h4", { className: "item-title", children: item.title }), _jsxs("p", { className: "item-sub", children: ["Sold by: ", item.category] }), _jsx("div", { className: "item-selectors", children: _jsxs("span", { className: "selector-chip", children: ["Qty: ", item.quantity] }) }), _jsx("div", { className: "item-price-row", children: _jsxs("span", { className: "current-price", children: ["$", (item.price * item.quantity).toFixed(2)] }) }), _jsxs("p", { className: "delivery-text", children: [_jsx("span", { style: { color: '#03a685' }, children: "\u2713" }), " Delivery by 28 Mar 2026"] })] }), _jsx("button", { className: "close-btn", onClick: () => removeFromCart(item.id), children: "\u2715" })] }, item.id)))] }), _jsxs("div", { className: "cart-summary-section", children: [_jsxs("p", { className: "summary-title", children: ["PRICE DETAILS (", cart.length, " Items)"] }), _jsxs("div", { className: "price-row", children: [_jsx("span", { children: "Total Price" }), _jsxs("span", { children: ["$", totalPrice.toFixed(2)] })] }), _jsxs("div", { className: "price-row", children: [_jsx("span", { children: "Platform Fee" }), _jsx("span", { className: "free-text", style: { color: '#03a685', fontWeight: 700 }, children: "FREE" })] }), _jsxs("div", { className: "price-row total-row", style: { borderTop: '1px solid #eaeaec', paddingTop: '15px', marginTop: '15px', fontWeight: 700 }, children: [_jsx("span", { children: "Total Amount" }), _jsxs("span", { children: ["$", totalPrice.toFixed(2)] })] }), _jsx("button", { className: "place-order-btn", children: "PLACE ORDER" })] })] }));
};
export default CartPage;
